"""GateKeeper DHCP 服务模块"""
import logging
import re
import threading
import subprocess
import os
import ipaddress

logger = logging.getLogger(__name__)

# dnsmasq 配置文件路径
DNSMASQ_CONF_PATH = "/etc/dnsmasq.d/gatekeeper.conf"
DNSMASQ_LEASE_FILE = "/var/lib/misc/dnsmasq.leases"


class DHCPService:
    """DHCP 服务管理（单例模式）"""
    _instance = None
    _lock = threading.Lock()

    def __new__(cls):
        with cls._lock:
            if cls._instance is None:
                cls._instance = super().__new__(cls)
                cls._instance._initialized = False
            return cls._instance

    def __init__(self):
        if self._initialized:
            return
        self._initialized = True
        self._enabled = False
        self._interface = None
        self._range_start = None
        self._range_end = None
        self._gateway = None
        self._dns_servers = ["8.8.8.8", "8.8.4.4"]
        self._lease_time = 86400
        self._leases = []
        logger.info("DHCP服务管理器初始化完成")

    def _validate_config(self, interface, range_start, range_end, gateway=None, dns_servers=None, lease_time=86400):
        """
        验证DHCP配置参数

        Raises:
            ValueError: 参数不合法时抛出
        """
        # 验证接口名格式
        if not interface or not re.match(r'^[a-zA-Z0-9_\-]+$', interface):
            raise ValueError("无效的接口名称: '{}'，仅允许字母、数字、下划线和连字符".format(interface))

        # 验证IP地址格式
        try:
            ipaddress.ip_address(range_start)
        except ValueError:
            raise ValueError("无效的起始IP地址: '{}'".format(range_start))

        try:
            ipaddress.ip_address(range_end)
        except ValueError:
            raise ValueError("无效的结束IP地址: '{}'".format(range_end))

        # 验证范围
        if ipaddress.ip_address(range_start) >= ipaddress.ip_address(range_end):
            raise ValueError("起始IP必须小于结束IP: {} >= {}".format(range_start, range_end))

        # 验证网关（如果提供）
        if gateway:
            try:
                ipaddress.ip_address(gateway)
            except ValueError:
                raise ValueError("无效的网关地址: '{}'".format(gateway))

        # 验证DNS服务器（如果提供）
        if dns_servers:
            for dns in dns_servers:
                try:
                    ipaddress.ip_address(dns)
                except ValueError:
                    raise ValueError("无效的DNS服务器地址: '{}'".format(dns))

        # 验证租约时间
        if not isinstance(lease_time, int) or lease_time < 60:
            raise ValueError("租约时间必须为正整数且不小于60秒")

    def configure(self, interface, range_start, range_end, gateway=None, dns_servers=None, lease_time=86400):
        """配置DHCP服务"""
        self._validate_config(interface, range_start, range_end, gateway, dns_servers, lease_time)
        self._interface = interface
        self._range_start = range_start
        self._range_end = range_end
        self._gateway = gateway
        self._dns_servers = dns_servers or ["8.8.8.8", "8.8.4.4"]
        self._lease_time = lease_time
        logger.info(f"DHCP配置已更新: {interface} {range_start}-{range_end}")

    def _generate_config(self):
        """生成dnsmasq配置文件"""
        if not self._interface or not self._range_start or not self._range_end:
            raise ValueError("DHCP未配置完整，需要interface、range_start、range_end")

        lines = [
            "# GateKeeper DHCP Configuration",
            "# Auto-generated by GateKeeper DHCP Service",
            "",
            "# 监听接口",
            "interface={}".format(self._interface),
            "bind-interfaces",
            "",
            "# DHCP地址池",
            "dhcp-range={},{},{}".format(self._range_start, self._range_end, self._lease_time),
        ]

        if self._gateway:
            lines.append("")
            lines.append("# 默认网关")
            lines.append("dhcp-option=option:router,{}".format(self._gateway))

        if self._dns_servers:
            lines.append("")
            lines.append("# DNS服务器")
            dns_str = ",".join(self._dns_servers)
            lines.append("dhcp-option=option:dns-server,{}".format(dns_str))

        lines.append("")
        lines.append("# 租约文件")
        lines.append("dhcp-leasefile={}".format(DNSMASQ_LEASE_FILE))
        lines.append("")
        lines.append("# 日志查询")
        lines.append("log-queries")
        lines.append("log-dhcp")

        config_content = "\n".join(lines) + "\n"

        try:
            # 确保目录存在
            conf_dir = os.path.dirname(DNSMASQ_CONF_PATH)
            if conf_dir and not os.path.exists(conf_dir):
                os.makedirs(conf_dir, exist_ok=True)

            with open(DNSMASQ_CONF_PATH, "w") as f:
                f.write(config_content)

            logger.info("dnsmasq配置文件已生成: {}".format(DNSMASQ_CONF_PATH))
            return True
        except PermissionError:
            logger.error("权限不足，无法写入配置文件: {}".format(DNSMASQ_CONF_PATH))
            return False
        except Exception as e:
            logger.error("生成配置文件失败: {}".format(e))
            return False

    def start(self):
        """启动DHCP服务"""
        try:
            # 生成配置文件
            if not self._generate_config():
                logger.error("启动DHCP服务失败: 配置文件生成失败")
                return False

            # 启动dnsmasq服务
            result = subprocess.run(
                ["systemctl", "start", "dnsmasq"],
                capture_output=True, text=True, timeout=30
            )
            if result.returncode != 0:
                # 尝试直接启动dnsmasq进程
                result = subprocess.run(
                    ["dnsmasq", "-C", DNSMASQ_CONF_PATH],
                    capture_output=True, text=True, timeout=10
                )
                if result.returncode != 0:
                    logger.error("启动dnsmasq失败: {}".format(result.stderr.strip()))
                    return False

            self._enabled = True
            logger.info("DHCP服务已启动")
            return True

        except FileNotFoundError:
            logger.error("dnsmasq未安装，请先安装: apt install dnsmasq")
            return False
        except subprocess.TimeoutExpired:
            logger.error("启动dnsmasq超时")
            return False
        except Exception as e:
            logger.error("启动DHCP服务失败: {}".format(e))
            return False

    def stop(self):
        """停止DHCP服务"""
        try:
            result = subprocess.run(
                ["systemctl", "stop", "dnsmasq"],
                capture_output=True, text=True, timeout=30
            )
            if result.returncode != 0:
                # 尝试直接kill dnsmasq进程
                result = subprocess.run(
                    ["killall", "dnsmasq"],
                    capture_output=True, text=True, timeout=10
                )

            self._enabled = False
            logger.info("DHCP服务已停止")
            return True

        except FileNotFoundError:
            logger.warning("systemctl或killall命令未找到")
            self._enabled = False
            return False
        except subprocess.TimeoutExpired:
            logger.error("停止dnsmasq超时")
            return False
        except Exception as e:
            logger.error("停止DHCP服务失败: {}".format(e))
            return False

    def restart(self):
        """重启DHCP服务"""
        logger.info("正在重启DHCP服务...")
        self.stop()
        return self.start()

    def get_leases(self):
        """读取dnsmasq租约文件获取租约列表"""
        leases = []
        try:
            if not os.path.exists(DNSMASQ_LEASE_FILE):
                logger.debug("租约文件不存在: {}".format(DNSMASQ_LEASE_FILE))
                return leases

            with open(DNSMASQ_LEASE_FILE, "r") as f:
                for line in f:
                    line = line.strip()
                    if not line or line.startswith("#"):
                        continue
                    # dnsmasq租约格式: <timestamp> <mac> <ip> <hostname> <client_id>
                    parts = line.split()
                    if len(parts) >= 4:
                        lease = {
                            "timestamp": int(parts[0]) if parts[0].isdigit() else 0,
                            "mac": parts[1],
                            "ip": parts[2],
                            "hostname": parts[3] if parts[3] != "*" else "",
                        }
                        leases.append(lease)

            self._leases = leases
            logger.debug("读取到 {} 条DHCP租约".format(len(leases)))
        except PermissionError:
            logger.error("权限不足，无法读取租约文件: {}".format(DNSMASQ_LEASE_FILE))
        except Exception as e:
            logger.error("读取DHCP租约失败: {}".format(e))

        return leases

    def get_status(self):
        """获取DHCP状态"""
        # 检查dnsmasq进程是否在运行
        is_running = False
        try:
            result = subprocess.run(
                ["pgrep", "-x", "dnsmasq"],
                capture_output=True, text=True, timeout=5
            )
            is_running = result.returncode == 0
        except Exception:
            pass

        return {
            "enabled": self._enabled,
            "running": is_running,
            "interface": self._interface,
            "range": f"{self._range_start} - {self._range_end}" if self._range_start else None,
            "gateway": self._gateway,
            "dns_servers": self._dns_servers,
            "lease_time": self._lease_time,
            "active_leases": len(self.get_leases()),
            "config_file": DNSMASQ_CONF_PATH,
        }
