"""GateKeeper 网络层 DNS 过滤模块"""
import collections
import logging
import re
import threading
import subprocess
import os

logger = logging.getLogger(__name__)

# unbound 配置文件路径
UNBOUND_CONF_PATH = "/etc/unbound/unbound.conf.d/gatekeeper.conf"
UNBOUND_MAIN_CONF = "/etc/unbound/unbound.conf"


class DNSFilter:
    """网络层DNS过滤管理（单例模式）"""
    _instance = None
    _lock = threading.Lock()

    def __new__(cls):
        with cls._lock:
            if cls._instance is None:
                cls._instance = super().__new__(cls)
                cls._instance._initialized = False
            return cls._instance

    def __init__(self):
        if self._initialized:
            return
        self._initialized = True
        self._enabled = False
        self._blocklists = {}
        self._allowlists = {}
        self._custom_rules = []
        self._dns_servers = ["8.8.8.8", "8.8.4.4"]
        self._query_log = collections.deque(maxlen=10000)
        self._listen_port = 53
        self._listen_interface = "0.0.0.0"
        self._upstream_dns = ["8.8.8.8", "8.8.4.4", "1.1.1.1"]
        logger.info("DNS过滤管理器初始化完成")

    def _validate_domain(self, domain):
        """
        验证域名格式

        Args:
            domain: 域名字符串

        Raises:
            ValueError: 域名格式不合法时抛出
        """
        if not domain or not isinstance(domain, str):
            raise ValueError("域名不能为空")
        if not re.match(r'^[a-zA-Z0-9_\-.]+$', domain):
            raise ValueError("无效的域名格式: '{}'，仅允许字母、数字、下划线、连字符和点".format(domain))
        if domain.startswith('.') or domain.endswith('.'):
            raise ValueError("域名不能以点开头或结尾: '{}'".format(domain))

    def add_domain_rule(self, domain, action="block", category="custom"):
        """添加域名规则"""
        self._validate_domain(domain)
        rule = {"domain": domain, "action": action, "category": category, "enabled": True}
        self._custom_rules.append(rule)
        logger.info(f"DNS规则已添加: {domain} -> {action}")
        # 如果服务正在运行，重新生成配置并重启
        if self._enabled:
            self._generate_config()
            self.restart()
        return rule

    def remove_domain_rule(self, domain):
        """移除域名规则"""
        self._custom_rules = [r for r in self._custom_rules if r.get("domain") != domain]
        logger.info(f"DNS规则已移除: {domain}")
        # 如果服务正在运行，重新生成配置并重启
        if self._enabled:
            self._generate_config()
            self.restart()

    def check_domain(self, domain):
        """检查域名是否被过滤 - 使用前缀点匹配避免部分匹配"""
        for rule in self._custom_rules:
            if rule.get("enabled"):
                rule_domain = rule.get("domain", "")
                # 使用前缀点进行后缀匹配，避免 notevil.com 匹配 evil.com
                if domain == rule_domain or domain.endswith("." + rule_domain):
                    return rule.get("action", "block")
        return "allow"

    def get_rules(self):
        """获取所有规则"""
        return list(self._custom_rules)

    def get_stats(self):
        """获取DNS过滤统计"""
        return {
            "enabled": self._enabled,
            "total_rules": len(self._custom_rules),
            "blocked_domains": len([r for r in self._custom_rules if r.get("action") == "block"]),
            "total_queries": len(self._query_log)
        }

    def _generate_config(self):
        """生成unbound配置文件"""
        lines = [
            "# GateKeeper DNS Filter Configuration",
            "# Auto-generated by GateKeeper DNS Filter",
            "",
            "server:",
            "    interface: {}".format(self._listen_interface),
            "    port: {}".format(self._listen_port),
            "    access-control: 10.0.0.0/8 allow",
            "    access-control: 172.16.0.0/12 allow",
            "    access-control: 192.168.0.0/16 allow",
            "    access-control: 0.0.0.0/0 refuse",
            "",
            "    # 上游DNS服务器",
        ]

        for dns in self._upstream_dns:
            lines.append("    forward-zone:")
            lines.append('        name: "."')
            lines.append("        forward-addr: {}".format(dns))

        lines.append("")
        lines.append("    # DNS缓存设置")
        lines.append("    cache-min-ttl: 300")
        lines.append("    cache-max-ttl: 86400")
        lines.append("    prefetch: yes")

        # 生成黑名单规则
        blocked_domains = [r for r in self._custom_rules if r.get("action") == "block" and r.get("enabled")]
        if blocked_domains:
            lines.append("")
            lines.append("    # 域名黑名单（GateKeeper规则）")
            for rule in blocked_domains:
                domain = rule.get("domain", "")
                if domain.startswith("*."):
                    # 通配符域名: 使用 local-zone 和 local-data
                    base = domain[2:]  # 去掉 *.
                    lines.append('    local-zone: "{}" redirect'.format(base))
                    lines.append('    local-data: "{} A 0.0.0.0"'.format(base))
                else:
                    lines.append('    local-zone: "{}" redirect'.format(domain))
                    lines.append('    local-data: "{} A 0.0.0.0"'.format(domain))

        config_content = "\n".join(lines) + "\n"

        try:
            # 确保目录存在
            conf_dir = os.path.dirname(UNBOUND_CONF_PATH)
            if conf_dir and not os.path.exists(conf_dir):
                os.makedirs(conf_dir, exist_ok=True)

            with open(UNBOUND_CONF_PATH, "w") as f:
                f.write(config_content)

            logger.info("unbound配置文件已生成: {}".format(UNBOUND_CONF_PATH))
            return True
        except PermissionError:
            logger.error("权限不足，无法写入配置文件: {}".format(UNBOUND_CONF_PATH))
            return False
        except Exception as e:
            logger.error("生成unbound配置文件失败: {}".format(e))
            return False

    def start(self):
        """启动unbound DNS过滤服务"""
        try:
            # 生成配置文件
            if not self._generate_config():
                logger.error("启动DNS过滤服务失败: 配置文件生成失败")
                return False

            # 启动unbound服务
            result = subprocess.run(
                ["systemctl", "start", "unbound"],
                capture_output=True, text=True, timeout=30
            )
            if result.returncode != 0:
                # 尝试直接启动unbound进程
                result = subprocess.run(
                    ["unbound", "-c", UNBOUND_CONF_PATH],
                    capture_output=True, text=True, timeout=10
                )
                if result.returncode != 0:
                    logger.error("启动unbound失败: {}".format(result.stderr.strip()))
                    return False

            self._enabled = True
            logger.info("DNS过滤服务已启动 (unbound)")
            return True

        except FileNotFoundError:
            logger.error("unbound未安装，请先安装: apt install unbound")
            return False
        except subprocess.TimeoutExpired:
            logger.error("启动unbound超时")
            return False
        except Exception as e:
            logger.error("启动DNS过滤服务失败: {}".format(e))
            return False

    def stop(self):
        """停止unbound DNS过滤服务"""
        try:
            result = subprocess.run(
                ["systemctl", "stop", "unbound"],
                capture_output=True, text=True, timeout=30
            )
            if result.returncode != 0:
                # 尝试直接kill unbound进程
                result = subprocess.run(
                    ["killall", "unbound"],
                    capture_output=True, text=True, timeout=10
                )

            self._enabled = False
            logger.info("DNS过滤服务已停止")
            return True

        except FileNotFoundError:
            logger.warning("systemctl或killall命令未找到")
            self._enabled = False
            return False
        except subprocess.TimeoutExpired:
            logger.error("停止unbound超时")
            return False
        except Exception as e:
            logger.error("停止DNS过滤服务失败: {}".format(e))
            return False

    def restart(self):
        """重启DNS过滤服务"""
        logger.info("正在重启DNS过滤服务...")
        self.stop()
        return self.start()

    def integrate_with_security_engine(self, security_dns_filter):
        """
        与security/dns_filter.py规则引擎集成
        将安全引擎中的规则同步到网络层DNS过滤

        Args:
            security_dns_filter: security.dns_filter.DNSFilterEngine实例
        """
        try:
            rules = security_dns_filter.get_rules(enabled_only=True)
            synced = 0
            for rule in rules:
                domain = rule.get("domain", "")
                action = rule.get("action", "block")
                if action in ("block", "redirect", "sinkhole"):
                    # 检查是否已存在
                    existing = [r for r in self._custom_rules if r.get("domain") == domain]
                    if not existing:
                        self._custom_rules.append({
                            "domain": domain,
                            "action": "block",
                            "category": rule.get("category", "security"),
                            "enabled": True,
                        })
                        synced += 1

            logger.info("从安全引擎同步了 {} 条DNS规则".format(synced))

            # 如果服务正在运行，重新生成配置
            if self._enabled:
                self._generate_config()
                self.restart()

            return {"synced": synced, "total": len(self._custom_rules)}

        except Exception as e:
            logger.error("同步安全引擎规则失败: {}".format(e))
            return {"synced": 0, "error": str(e)}
